// Include this

#include "/Engine/Public/Platform.ush"

// Read-write textures
#define SPECTRUM_TEX_SIZE 128
#define  GRAVITY 9.81f
#define SEED 12345
#define LOWCUTOFF 0.0001f
#define HIGHCUTOFF 9000.0f
#define DEPTH 500.f
#define PI 3.14159265359f


	RWTexture2D<float4> OutputTexture;
	float scale;
	float angle;
	float spreadBlend;
	float swell;
	float alpha;
	float peakOmega;
	float gamma;
	float shortWavesFade;


float hash(uint n) {
	// integer hash copied from Hugo Elias
	n = (n << 13U) ^ n;
	n = n * (n * n * 15731U + 0x789221U) + 0x1376312589U;
	return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}

float2 UniformToGaussian(float u1, float u2) {
	float R = sqrt(-2.0f * log(u1));
	float theta = 2.0f * PI * u2;

	return float2(R * cos(theta), R * sin(theta));
}

float Dispersion(float kMag) {
    return sqrt(GRAVITY * kMag * tanh(min(kMag * DEPTH, 20)));
}

float DispersionDerivative(float kMag) {
    float th = tanh(min(kMag * DEPTH, 20));
    float ch = cosh(kMag * DEPTH);
    return GRAVITY * (DEPTH * kMag / ch / ch + th) / Dispersion(kMag) / 2.0f;
}

float NormalizationFactor(float s) {
    float s2 = s * s;
    float s3 = s2 * s;
    float s4 = s3 * s;
    if (s < 5) return -0.000564f * s4 + 0.00776f * s3 - 0.044f * s2 + 0.192f * s + 0.163f;
    else return -4.80e-08f * s4 + 1.07e-05f * s3 - 9.53e-04f * s2 + 5.90e-02f * s + 3.93e-01f;
}

float DonelanBannerBeta(float x) {
	if (x < 0.95f) return 2.61f * pow(abs(x), 1.3f);
	if (x < 1.6f) return 2.28f * pow(abs(x), -1.3f);

	float p = -0.4f + 0.8393f * exp(-0.567f * log(x * x));
	return pow(10.0f, p);
}

float DonelanBanner(float theta, float omega, float peakOmega) {
	float beta = DonelanBannerBeta(omega / peakOmega);
	float sech = 1.0f / cosh(beta * theta);
	return beta / 2.0f / tanh(beta * 3.1416f) * sech * sech;
}

float Cosine2s(float theta, float s) {
	return NormalizationFactor(s) * pow(abs(cos(0.5f * theta)), 2.0f * s);
}

float SpreadPower(float omega, float peakOmega) {
	if (omega > peakOmega)
		return 9.77f * pow(abs(omega / peakOmega), -2.5f);
	else
		return 6.97f * pow(abs(omega / peakOmega), 5.0f);
}

float DirectionSpectrum(float theta, float omega) {
	float s = SpreadPower(omega, peakOmega) + 16 * tanh(min(omega / peakOmega, 20)) * swell * swell;
	return lerp(2.0f / 3.1415f * cos(theta) * cos(theta), Cosine2s(theta - angle, s), spreadBlend);
}

float TMACorrection(float omega) {
	float omegaH = omega * sqrt(DEPTH / GRAVITY);
	if (omegaH <= 1.0f)
		return 0.5f * omegaH * omegaH;
	if (omegaH < 2.0f)
		return 1.0f - 0.5f * (2.0f - omegaH) * (2.0f - omegaH);

	return 1.0f;
}

float JONSWAP(float omega) {
	float sigma = (omega <= peakOmega) ? 0.07f : 0.09f;

	float r = exp(-(omega - peakOmega) * (omega - peakOmega) / 2.0f / sigma / sigma / peakOmega / peakOmega);
	
	float oneOverOmega = 1.0f / omega;
	float peakOmegaOverOmega = peakOmega / omega;
	return scale * TMACorrection(omega) * alpha * GRAVITY * GRAVITY
		* oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega
		* exp(-1.25f * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega)
		* pow(abs(gamma), r);
}

float ShortWavesFade(float kLength) {
	return exp(-shortWavesFade * shortWavesFade * kLength * kLength);
}

[numthreads(8,8,1)]
void MainCS(uint3 id : SV_DispatchThreadID) {
    uint seed = id.x + SPECTRUM_TEX_SIZE * id.y + SPECTRUM_TEX_SIZE;
    seed += SEED;

	const uint lenghtScale = SPECTRUM_TEX_SIZE / 8;

    for (uint i = 0; i < 4; ++i) {
            float halfN = SPECTRUM_TEX_SIZE / 2.0f;

        float deltaK = 2.0f * PI / lenghtScale;
        float2 K = (id.xy - halfN) * deltaK;
        float kLength = length(K);

        seed += i + hash(seed) * 10;
        float4 uniformRandSamples = float4(hash(seed), hash(seed * 2), hash(seed * 3), hash(seed * 4));
        float2 gauss1 = UniformToGaussian(uniformRandSamples.x, uniformRandSamples.y);
        float2 gauss2 = UniformToGaussian(uniformRandSamples.z, uniformRandSamples.w);

        if (LOWCUTOFF <= kLength && kLength <= HIGHCUTOFF) {
            float kAngle = atan2(K.y, K.x);
            float omega = Dispersion(kLength);

            float dOmegadk = DispersionDerivative(kLength);

            float spectrum = JONSWAP(omega) * DirectionSpectrum(kAngle, omega) * ShortWavesFade(kLength);
            
            /*if (_Spectrums[i * 2 + 1].scale > 0)
                spectrum += JONSWAP(omega, spectrum) * DirectionSpectrum(kAngle, omega, spectrum) * ShortWavesFade(kLength, spectrum);*/
            
            OutputTexture[id.xy] = float4(float2(gauss2.x, gauss1.y) * sqrt(2 * spectrum * abs(dOmegadk) / kLength * deltaK * deltaK), 0.0f, 0.0f);
        } else {
            OutputTexture[id.xy] = 0.0f;
        }
    }
}


/*[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void MainCS(uint3 Gid : SV_GroupID, //atm: -, 0...256, - in rows (Y)        --> current group index (dispatched by c++)
                       uint3 DTid : SV_DispatchThreadID) //atm: 0...256 in rows & columns (XY)   --> "global" thread id

{   
    
    float3 p = DTid.xyz;
    int multiplier = 2;
    float k = 2 * 3.14159265359 / 10;
    float height = sin(k * DTid.x);

    
    OutputTexture[DTid.xy] = float4(0.f, height, 0.f, 1.f);
}*/
